In [2]:
import numpy as np

def gram_schmidt(A):
    """
    Realiza la factorización QR de una matriz A utilizando el método de Gram-Schmidt.

    :param A: Matriz rectangular.
    :return: Matrices Q (ortogonal) y R (triangular superior).
    """
    m, n = A.shape
    Q = np.zeros((m, n), dtype=np.float64)  # Especificar dtype=float64
    R = np.zeros((n, n), dtype=np.float64)  # Especificar dtype=float64

    for j in range(n):
        v = A[:, j].copy().astype(np.float64)  # Convertir a float64

        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]

        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

# Ejemplo de uso:
if __name__ == "__main__":
    # Definir una matriz rectangular
    A = np.array([[1, 4],
                  [2, 5],
                  [3, 6]])

    # Realizar la factorización QR
    Q, R = gram_schmidt(A)

    # Mostrar resultados
    print("Matriz Q (ortogonal):")
    print(Q)
    print("\nMatriz R (triangular superior):")
    print(R)

    # Verificar que Q * R es aproximadamente igual a la matriz original A
    reconstructed_A = np.dot(Q, R)
    print("\nReconstrucción de A con Q * R:")
    print(reconstructed_A)


Matriz Q (ortogonal):
[[ 0.26726124  0.87287156]
 [ 0.53452248  0.21821789]
 [ 0.80178373 -0.43643578]]

Matriz R (triangular superior):
[[3.74165739 8.55235974]
 [0.         1.96396101]]

Reconstrucción de A con Q * R:
[[1. 4.]
 [2. 5.]
 [3. 6.]]
