In [1]:
import numpy as np

def es_no_singular(matriz):
    determinante = np.linalg.det(matriz)
    return determinante != 0

def obtener_inversa(matriz):
    if es_no_singular(matriz):
        inversa = np.linalg.inv(matriz)
        return inversa
    else:
        return None

# Matriz 1
matriz1 = np.array([
    [4, 2, 6],
    [3, 0, 7],
    [-2, -1, -3]
])

# Matriz 2
matriz2 = np.array([
    [1, 2, 3, 4],
    [2, 1, -1, 1],
    [-3, 2, 0, 1],
    [0, 5, 2, 6]
])

# Matriz 3
matriz3 = np.array([
    [2, 0, 1, 2],
    [1, 1, 0, 2],
    [2, -1, 3, 1],
    [3, -1, 4, 3]
])

# Verificar si son no-singulares y obtener inversas si es posible
print("Matriz 1:")
if es_no_singular(matriz1):
    inversa1 = obtener_inversa(matriz1)
    print(f"La matriz es no-singular. Inversa:\n{inversa1}")
else:
    print("La matriz es singular y no tiene inversa.")

print("\nMatriz 2:")
if es_no_singular(matriz2):
    inversa2 = obtener_inversa(matriz2)
    print(f"La matriz es no-singular. Inversa:\n{inversa2}")
else:
    print("La matriz es singular y no tiene inversa.")

print("\nMatriz 3:")
if es_no_singular(matriz3):
    inversa3 = obtener_inversa(matriz3)
    print(f"La matriz es no-singular. Inversa:\n{inversa3}")
else:
    print("La matriz es singular y no tiene inversa.")


Matriz 1:
La matriz es singular y no tiene inversa.

Matriz 2:
La matriz es singular y no tiene inversa.

Matriz 3:
La matriz es no-singular. Inversa:
[[ 1.00000000e+00  7.40148683e-17  1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  1.66666667e+00  1.66666667e+00 -1.00000000e+00]
 [-1.00000000e+00  6.66666667e-01  6.66666667e-01 -0.00000000e+00]
 [-0.00000000e+00 -3.33333333e-01 -1.33333333e+00  1.00000000e+00]]
