In [1]:
import numpy as np

# Definir las matrices
matrix1 = np.array([[1, 1, 2],
                    [4, 1, 5],
                    [0, 0, 1]])

matrix2 = np.array([[10, 0, 0],
                    [1, -3, -7],
                    [0, 2, 6]])

# Función para aplicar el método QR
def qr_method(matriz, max_iter=1000, tol=1e-10):
    n = matriz.shape[0]
    A = np.copy(matriz)

    for _ in range(max_iter):
        Q, R = np.linalg.qr(A)
        A = R @ Q

        # Verificar convergencia
        if np.linalg.norm(np.triu(A, k=1)) < tol:
            break

    # Extraer valores y vectores característicos
    eigenvalues = np.diagonal(A)
    eigenvectors = np.eye(n)

    for i in range(n):
        for j in range(max_iter):
            eigenvectors[:, i] = Q @ eigenvectors[:, i]

    return eigenvalues, eigenvectors

# Aplicar el método QR a la Matriz 1
eigenvalues1, eigenvectors1 = qr_method(matrix1)

# Aplicar el método QR a la Matriz 2
eigenvalues2, eigenvectors2 = qr_method(matrix2)

# Imprimir resultados para la Matriz 1
print("Matriz 1:")
print("Valores Característicos:", eigenvalues1)
print("Vectores Característicos:")
print(eigenvectors1)

# Imprimir resultados para la Matriz 2
print("\nMatriz 2:")
print("Valores Característicos:", eigenvalues2)
print("Vectores Característicos:")
print(eigenvectors2)


Matriz 1:
Valores Característicos: [ 3. -1.  1.]
Vectores Característicos:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz 2:
Valores Característicos: [10.  4. -1.]
Vectores Característicos:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
