In [4]:
import numpy as np
from scipy.linalg import lu, solve

def resolver_sistema_lu(A, b):
    # Obtener la descomposición LU con pivoteo parcial
    p, lu_matrix = lu(A, permute_l=True)

    # Descomponer la matriz LU
    l = np.tril(lu_matrix, k=-1) + np.eye(len(A))
    u = np.triu(lu_matrix)

    # Resolver Ly = Pb usando sustitución hacia adelante
    y = solve(l, np.dot(p, b), assume_a="gen")

    # Resolver Ux = y usando sustitución hacia atrás
    x = solve(u, y, assume_a="gen")

    return l, u, x

# Sistema 1
A1 = np.array([
    [6, 2, 1, -1],
    [2, 4, 1, 0],
    [1, 1, 4, -1],
    [-1, 0, -1, 3]
])
b1 = np.array([0, 7, -1, -2])

l1, u1, solucion_sistema1 = resolver_sistema_lu(A1, b1)
print("Matriz L del sistema 1:")
print(l1)
print("\nMatriz U del sistema 1:")
print(u1)
print("\nSolución del sistema 1:")
print(solucion_sistema1)

# Sistema 2
A2 = np.array([
    [2, -1, 0, 0, 0],
    [1, 2, -1, 0, 0],
    [0, 2, 4, -1, 0],
    [0, 0, 0, 2, -1],
    [0, 0, 0, 1, 2]
])
b2 = np.array([1, 2, -1, -2, -1])

l2, u2, solucion_sistema2 = resolver_sistema_lu(A2, b2)
print("\nMatriz L del sistema 2:")
print(l2)
print("\nMatriz U del sistema 2:")
print(u2)
print("\nSolución del sistema 2:")
print(solucion_sistema2)


Matriz L del sistema 1:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matriz U del sistema 1:
[[ 6.          2.          1.         -1.        ]
 [ 0.          3.33333333  0.66666667  0.33333333]
 [ 0.          0.          3.7        -0.9       ]
 [ 0.          0.          0.          2.58108108]]

Solución del sistema 1:
[-0.78273666  2.13923872  0.00851847 -0.40942408]

Matriz L del sistema 2:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Matriz U del sistema 2:
[[ 2.  -1.   0.   0.   0. ]
 [ 0.   2.5 -1.   0.   0. ]
 [ 0.   0.   4.8 -1.   0. ]
 [ 0.   0.   0.   2.  -1. ]
 [ 0.   0.   0.   0.   2.5]]

Solución del sistema 2:
[ 0.96666667  0.93333333 -0.16666667 -1.4        -0.8       ]
