In [2]:
import numpy as np

# Matriz 1
matrix1 = np.array([[3, 2, -1],
                    [1, -2, 3],
                    [2, 0, 4]])

# Matriz 2
matrix2 = np.array([[2, 1, 1],
                    [2, 3, 2],
                    [1, 1, 2]])

# Función para obtener los valores característicos y vectores característicos
def obtener_caracteristicas(matriz):
    eigenvalues, eigenvectors = np.linalg.eig(matriz)
    return eigenvalues, eigenvectors

# Obtener los valores característicos y vectores característicos para la Matriz 1
eigenvalues1, eigenvectors1 = obtener_caracteristicas(matrix1)

# Obtener los valores característicos y vectores característicos para la Matriz 2
eigenvalues2, eigenvectors2 = obtener_caracteristicas(matrix2)

# Imprimir resultados para la Matriz 1
print("Matriz 1:")
print("Valores Característicos:", eigenvalues1)
print("Vectores Característicos:")
print(eigenvectors1)

# Imprimir resultados para la Matriz 2
print("\nMatriz 2:")
print("Valores Característicos:", eigenvalues2)
print("Vectores Característicos:")
print(eigenvectors2)


Matriz 1:
Valores Característicos: [ 3.  4. -2.]
Vectores Característicos:
[[-4.08248290e-01 -1.81298661e-16  3.48742916e-01]
 [ 4.08248290e-01  4.47213595e-01 -9.29981110e-01]
 [ 8.16496581e-01  8.94427191e-01 -1.16247639e-01]]

Matriz 2:
Valores Característicos: [1. 5. 1.]
Vectores Característicos:
[[-0.80178373  0.40824829 -0.29474362]
 [ 0.53452248  0.81649658 -0.51205571]
 [ 0.26726124  0.40824829  0.80679933]]
